spring.application.name=appointment


logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/medserve
spring.datasource.username=root
spring.datasource.password=2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# spring.web.resources.static-locations=classpath:/static/


# Configuration corrigée des ressources statiques
spring.web.resources.static-locations=classpath:/static/,file:./uploads/
spring.mvc.static-path-pattern=/**

server.port=8081
logging.level.org.springframework.web=DEBUG

logging.level.com.medical.appointment=TRACE
server.error.include-stacktrace=always
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Activer la suppression automatique des fichiers temporaires
spring.servlet.multipart.resolve-lazily=true